### ISSUE TITLE
A2Q1 IMAGES and DATA ANALYSIS directory

### ISSUE THREAD

**Issue by JinyuruY** [BME1478H/Winter2022class#388]
Hi,

For assignment2 question 1 are we supposed to create the images and data analysis directories at the same level as the assignment-data, or can we create these two directories within the assignment-data directory?

I am assuming the TA when checking our code will be working from the assignment-data folder as their pwd? Thanks!

**Comment by amostof** [comment]
Hello,
I believe the former. The three directories would be at the same level.
