### ISSUE TITLE
Command & 

### ISSUE THREAD

**Issue by wennzhao** [BME1478H/Winter2022class#389]
I have no idea how to use command "**&**" in bash. 
Could someone give me some examples to explain that _**&** runs the previous command in the "background"_?

**Comment by DavidCromp** [comment]
Say you have a file that will take some time to download, with say `wget`

You can use the `&` to do something like the following:
```bash
wget https://URL &
mkdir DIRECTORY
cd DIRECTORY
touch file```

While `wget` downloads the file you'll be able to continue doing things in the commandline without disruption

**Comment by RayNele** [comment]
great explanation @DavidCromp
