### ISSUE TITLE
Syllabus question

### ISSUE THREAD

**Issue by daniellekarakas** [BME1478H/Winter2022class#413]
I have a few questions about the BME1478 syllabus as there are some discrepancies on Quercus. The home page says “Each week will include a set of associated exercises, each set worth 6% of the total course grade. A final assignment will also be required, worth 28% of the total grade.” Assignments for weeks 2 and onwards are shown as 8 marks on Quercus versus 6. Does this mean each weekly assignment has more weighting than stipulated in the syllabus, and is the final assignment worth less as a result? Will our final assignment be assigned as our week 12 assignment, or in addition to week 12? 

Thanks in advance.

**Comment by RayNele** [comment]
The number of marks per assignment is unrelated to % of final grade

**Comment by daniellekarakas** [comment]
@RayNele Thanks!
