### ISSUE TITLE
Running Command not found

### ISSUE THREAD

**Issue by wennzhao** [BME1478H/Winter2022class#419]
![image](https://user-images.githubusercontent.com/97702126/153775703-4810e355-8179-4a3f-a6c1-3a1056a83c3d.png)

When I try to use **running** in bash, it shows command not found.

**Comment by RayNele** [comment]
I don't have that command either. More context on what you're trying to accompish would help

**Comment by wennzhao** [comment]
I am trying to practice with week_5 lecture slide p.8
Already had scripts on stats_02.py and try to run it on bash.

![image](https://user-images.githubusercontent.com/97702126/153777124-44263b59-5702-4a7f-aefd-2c9e169b4427.png)

![image](https://user-images.githubusercontent.com/97702126/153776996-61387ddf-783c-465f-bc06-edc1a3bab539.png)

**Comment by QinJi23** [comment]
Pretty sure the "running" is an output of the python file telling you that the python code is running. There is no bash coming called running. You might have some output option turned off in bash. I could be wrong.

**Comment by wennzhao** [comment]
Thanks, I found this as well. 
Do you know how can I running the python code like p.8 on slide, and get the results with 60 rows?

**Comment by wennzhao** [comment]
Thanks all,
I‘ve solved it.
