### ISSUE TITLE
Assignment 10 plt.plot issue - 'tuple' object is not callable

### ISSUE THREAD

**Issue by d-jokic** [BME1478H/Winter2022class#524]
x = world_data_2014.child_mortality
        y = world_data_2014.life_expectancy
        
        x = sm.add_constant(x)
        
        model = sm.OLS(y,x)
        results = model.fit()
        
        sns.scatterplot(x='child_mortality', y='life_expectancy', data=world_data_2014)
        plt.plot(world_data_2014.child_mortality,results.fittedvalues)

When I run this code I get the following error, and the linear regression line does not show up on the graph: 
<img width="477" alt="image" src="https://user-images.githubusercontent.com/22248638/160419150-794e29d5-e49c-4dfd-9f49-e31e59f88a7c.png">

I edited lesson10.ipynb to do the same thing, and it works fine, so I don't think its related to the version of python I have. I haven't changed the first cell (class and data imports). Does anyone else have this problem?

**Comment by RayNele** [comment]
Works for me. You probably did something weird with the world_data_2014 dataset somewhere in another cell. 

I recommend stopping/restarting the kernel and trying again. Update me with any progress :)

**Comment by d-jokic** [comment]
Thank you! I thought clearing outputs would be enough but restarting the kernel fixed it
