### ISSUE TITLE
A11 Part 2d

### ISSUE THREAD

**Issue by Stern49** [BME1478H/Winter2022class#527]
Hi,

I am currently working on Assignment 11 Part 2 Question d. I am a bit confused what the question is asking. The question is asking to plot 2 plots as shown below.
![image](https://user-images.githubusercontent.com/97901521/161116238-89c0b256-c451-4a3d-b9be-ec1e6da0a256.png)

I am a bit confused whether these 2 plots should be on one or two figures and what exactly the second plot is asking for.

This is what I have tried so far. Please let me know if this is correct or if there is something I am missing.
![image](https://user-images.githubusercontent.com/97901521/161116544-3aa555a7-935a-4426-8f64-14d23069ecc6.png)

Thank you.

**Comment by RayNele** [comment]
plot the prediction and the actual data on the same plot. what you have is fine
