### ISSUE TITLE
Q11 3a ValueError

### ISSUE THREAD

**Issue by pganga5506** [BME1478H/Winter2022class#531]
In Question 3a of Assignment 11, we need to create a new variable df after dropping the unwanted columns of 'country', 'sub_region', and 'income_group'. We're then asked to append `.dropna(how=any, axis=0)` to this line of code to clean our data and remove rows with null values. 

The dropna() function is causing me to have ValueError and it seems it could be because the 'how' attribute is set to 'any'. I tried setting it to 'None' but I got the TypeError this time (TypeError: must specify how or thresh).

I think we are supposed to use how=any as the question asks us to use this. It'd be great if you could hep me with this issue.

Here's the code I'm using:

df = new_world_data.drop(columns=['country', 'sub_region', 'income_group']).dropna(how=any, axis=0)

#keep this code here
df.head()

I've also attached the screenshot of the error.
![Screenshot 2022-04-05 1 15 31 PM](https://user-images.githubusercontent.com/61210052/161835413-db48ada5-b2aa-4db8-aa74-072157a7d906.png)

**Comment by d-jokic** [comment]
Instead of any I put 'any' and it worked.

**Comment by pganga5506** [comment]
> Instead of any I put 'any' and it worked.

That worked. Thank you! :)
