### ISSUE TITLE
A11 Q2d

### ISSUE THREAD

**Issue by rLukose99** [BME1478H/Winter2022class#532]
Hello,

For question 2d on assignment 11, I was wondering whether you were expecting the plots to be placed side by side using subplots (actual and predicted), or whether the plots are intended to be overlaid on top of one another as we did in assignment 10?

Thank you.

**Comment by rLukose99** [comment]
I guess ill just pick one way and submit...

**Comment by RayNele** [comment]
#527 should help

**Comment by rLukose99** [comment]
Thank you so much! I must've missed that when looking through the issues a few days ago.
